#!/usr/bin/env bash
# Points packaging/aur/PKGBUILD at a published release: sets pkgver, fills in the checksum of the
# source tarball from dist/SHA256SUMS (or from the published release), and regenerates .SRCINFO.
#
#   bash packaging/aur.sh 0.1.0
#
# Submitting to the AUR needs the maintainer's own SSH key, registered on aur.archlinux.org, so
# this script only prepares the files. packaging/aur/README.md has the four commands that publish.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${1:-${DHS_VERSION:-}}"
[ -n "$VERSION" ] || { echo "usage: bash packaging/aur.sh <version>"; exit 1; }
VERSION="${VERSION#v}"

TARBALL="dhs-${VERSION}-source.tar.gz"
SUM=""

# Prefer the checksum computed at build time; otherwise take it from the published release.
if [ -f "dist/SHA256SUMS" ]; then
  SUM="$(awk -v f="./$TARBALL" '$2 == f {print $1}' dist/SHA256SUMS)"
fi
if [ -z "$SUM" ]; then
  URL="https://github.com/Necta14/dhs/releases/download/v${VERSION}/${TARBALL}"
  echo "── checksum not in dist/, hashing $URL"
  SUM="$(curl -fsSL "$URL" | sha256sum | cut -d' ' -f1)"
fi
[ -n "$SUM" ] || { echo "could not determine the checksum of $TARBALL"; exit 1; }

cd packaging/aur
sed -i -E "s/^pkgver=.*/pkgver=${VERSION}/" PKGBUILD
sed -i -E "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
sed -i -E "s/^sha256sums=\('.*'\)/sha256sums=('${SUM}')/" PKGBUILD

if command -v makepkg >/dev/null 2>&1; then
  makepkg --printsrcinfo > .SRCINFO
  echo "── .SRCINFO regenerated by makepkg"
else
  # A split package's .SRCINFO has one pkgname stanza per output and is not worth hand-writing:
  # get it wrong and the AUR rejects the push. makepkg comes with pacman on any Arch system.
  echo "── .SRCINFO NOT regenerated: makepkg is not on this host."
  echo "   Run 'makepkg --printsrcinfo > .SRCINFO' in packaging/aur/ on an Arch machine"
  echo "   before pushing, or the AUR will refuse the commit."
fi

echo "   pkgver   ${VERSION}"
echo "   sha256   ${SUM}"
